# Generated by Django 5.1.1 on 2024-09-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
