# Generated by Django 5.1.1 on 2024-09-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0005_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
    ]
